### ISSUE TITLE
NSS: Merge openSUSE / SUSE

### ISSUE THREAD

**Issue by msirringhaus** [openSUSE/firefox-maintenance#2]
There are two ways to do this:

1.) Have hmac-packages on openSUSE as well. Then we can just copy all from SUSE.
2.) Only build hmac-packages for SUSE doing `if 0%{?suse_version} && !0%{?is_opensuse}`

**General questions**

a) `baselibs.conf` on SUSE-side has an additional requirement under mozilla-nss:
```
  requires "mozilla-nspr-<targettype> >= 4.20"
```

b) How to merge changelog?

**Questions for option 2.)**
`baselibs.conf` on SUSE-side splits libsofttokn3 and libfreebl3 into 2 packages:
```
libsoftokn3
  requires "libfreebl3-<targettype> = <version>"
libsoftokn3-hmac
  +/usr/lib/libsoftokn3.chk
  +/usr/lib/libnssdbm3.chk
libfreebl3
libfreebl3-hmac
  +/lib/libfreebl3.chk
  +/lib/libfreeblpriv3.chk
```
c) Is there a way to have a conditional in this `baselibs.conf` to differentiate between openSUSE and SUSE?
d) The very last line `  +/lib/libfreeblpriv3.chk` is not present in openSUSE. Why?

**Comment by wrosenauer** [comment]
What is the rationale behind having those hmac packages? Currently I cannot tell if we should just have that in openSUSE or not. But anyway this seems to be a simple condition to have in any case.

About baselibs.conf I think this is a total valid improvement in package requirements which just didn't cause a visible issue in openSUSE yet.

I cannot answer the question c)
d) I cannot answer that either. It might be something I just forgot to add at some point and no issues were reported yet? In general the baselibs are not really in focus because with the normal OBS setup you cannot even get those packages for Leap since x86 cannot be built. I asked a few times in the past how to create baselibs packages in OBS for Leap but never got the answer and finally gave up because in real life it seems to be less and less important.

**Comment by wrosenauer** [comment]
The latest NSS package in mozilla:Factory has a few things merged (especially the baselibs stuff).
The -hmac subpackages are still under evaluation. I try to get more information why they exist from other SUSE contacts who might know.

**Comment by msirringhaus** [comment]
There might be a problem merging the hmac-packages back in.
I found this: https://csrc.nist.gov/CSRC/media/projects/cryptographic-module-validation-program/documents/security-policies/140sp2622.pdf
I'm not familiar with the FIPS-stuff, but that document explicitly mentions the hmac-packages, so removing them might invalidate the FIPS-certificate for SLE-12?

**Comment by wrosenauer** [comment]
In that case given that NSS in Leap is coming from SLE and has those packages I assume there is no restriction to use the same schema in openSUSE.
So before spending more months on that topic I would prepare the next NSS package in Factory using the same package structure. Agreed?

**Comment by msirringhaus** [comment]
Asked M. Meissner and he prefers to keep it as it is. So: Agreed!

**Comment by wrosenauer** [comment]
mozilla:Factory/mozilla-nss now contains a package which is almost totally in sync with the SLE version.
I decided to change the Suggests to Recommends which usually makes sure to get the -hmac packages installed to openSUSE users because they had the files before. I think this should not make a difference for SLE.
Also the changelog now is quite different.
So not sure which version now to track in this repo actually but I would propose that all of us keep mozilla:Factory up to date from now on and avoid to deviate away from that again.

**Comment by msirringhaus** [comment]
Could you check in your nss.spec? 

changelogs are indeed tricky. I would suggest to close this bug with the spec-checkin and open a new one about changelogs, as this will affect all packages. In there we can discuss options.
