### ISSUE TITLE
Merge Thunderbird

### ISSUE THREAD

**Issue by msirringhaus** [openSUSE/firefox-maintenance#5]
Only questionmark here is again the used rust-version.

Also `mozilla-bmo1519629.patch` puzzles me a bit. We don't have it, but building with rust 1.34, which seems to work fine.
According to bugzilla, the fix for this is not in the ESR-version. Not sure why its there.

But it can probably safely be removed, once Thunderbird 68 comes along.

**Comment by wrosenauer** [comment]
I cannot tell why you don't need mozilla-bmo1519629.patch. In the "mozilla" OBS project it's certainly required to make it build. It's likely a combination of the different mixed toolchains in that repo required to support older distributions. But as you mentioned with TB 68 it should just go away.

**Comment by wrosenauer** [comment]
About rust version in general.
The dependencies I code into the the openSUSE specs is the minimal requirement found in the mozilla sources.
I think I noticed at some point is that on certain architectures you might need a newer rust version because of platform dependencies. In my opinion those still should not be coded in the TB spec file though.

**Comment by msirringhaus** [comment]
FYI: I branched in obs and removed that patch for testing. 
Indeed, all Leap-version build, but all Factory-versions fail.

**Comment by msirringhaus** [comment]
Current spec seems to work for Factory, but I get a lot of OOM-kills or other out of memory errors, even with 12GB RAM.

**Comment by msirringhaus** [comment]
Done with #21
